version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: wit_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: wit_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wit_user -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - wit_network

networks:
  wit_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
